Shopify/shopify-app-template-remix

app/routes/app._index.jsx, app/routes/app.jsx, tsconfig.json
This PR includes `@shopify/app-bridge-types` globally rather than requiring imports in every file.
=> fix(types): include @shopify/app-bridge-types globally

app/routes/app._index.jsx
Currently, we're marking the button as loading any time the page loads, e.g. on a navigation. Let's restrict that to POST only.
=> Fix generate product button loading state

README.md, app/routes/app._index.jsx, app/routes/app.additional.jsx, app/routes/app.jsx
This PR uses a link translation object to allow using Polaris `Link`s in embedded apps.
=> Use Polaris-to-Remix link translation component

README.md
There's been a couple of instances where folks changed their scopes but didn't run `config push` to update Shopify with the new value, which leads into an OAuth loop because the app never gets the scopes it expects to when going through OAuth.
To help mitigate the issue, I'm adding a gotcha section to the README to indicate that developers would need to run the `push` command when they change their scopes.
=> Add gotcha section about config push command

.github/CODEOWNERS, .github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .github/dependabot.yml, .github/workflows/cla.yml
This PR adds some missing items from the `.github` folder, to make it easier for folks to report issues, and adds the Shopify CLA as a requirement for external contributions.
=> Add github workflows and meta-docs

.github/workflows/remove-labels-on-activity.yml
When we request a response from partners, we also add a `Waiting for response` labels. This workflow will automatically remove that label when a comment is created on the issue so we get notified.
=> Remove waiting for response label on comment creation

app/routes/app._index.jsx
We don't need to parse the `session.shop` in the loader just to then construct a URL in the component.  Instead, we can use [App Bridge](https://shopify.dev/docs/api/app-bridge-library/reference/navigation#navigating-to-pages-in-the-shopify-admin-/products-page-with-resource)
1. Remove the logic from the loader.  I kept `shopify.authenticate` just because I think it's one of the first things users will want to mess with, but technically it doesn't need to be there because we have the layout.
2. Update the product URL to App Bridge's special schema
1. Click generate a product
2. Click View product.
The product should open in a new tab.
- ~~[ ] I have added/updated tests for this change~~
- ~~[ ] I have made …
=> Simplify navigation using App Bridge

package.json
This PR is enhancing the `docker-start` command to run the full prisma setup to ensure the client matches development on Docker environments.
=> Run the full setup cmd on docker-start

package.json
Without these types packages, every JSX element get's red squgglies:
```
Type 'Element' is not assignable to type 'ReactNode'.ts(2322)
```
Adding these packages fixes them.
Adds 2 type packages
=> Add React type packages

.github/workflows/convert-to-js.yml, app/routes/app._index.tsx, app/routes/app.additional.tsx
The JS conversion workflow wasn't properly updating git history, so the PR ended up containing some unwanted history.
Changing the process slightly so we always use a fresh local branch, and push that over the `javascript_updates` branch.
=> Improve JS conversion workflow

package.json
Adds support for Bun as as package manager (https://github.com/Shopify/cli/pull/3006).
- Adds an empty extensions folder, because it's defined as the workspaces folder and Bun crashes if it doesn't exist
- Adds plugin-cloudflare as a trusted dependency in package.json, which is required by Bun to run the postinstall script than downloads the Cloudflare binary
=> Support for Bun

package.json
Closes #407
`@shopify/shopify-api` needs to be a direct dependency of this project because we're directly importing from it, so we need to make sure the version we end up using matches our expectation.
Not having this breaks when using `pnpm` because `@shopify/app` also has a dependency on the library, but on version 7, which confuses `pnpm`.
Adding the dependency.
=> Add direct dependency for shopify-api

.github/workflows/convert-to-js.yml
This PR fixes an issue with the workflow to convert the code to Javascript, where we restored `package.json` after we edited the build command to work in it. This change makes us restore it _and then_ update the command.
=> Fix issue in workflow to convert code to JS

package.json
Reverts Shopify/shopify-app-template-remix#452
CI on the PR was passing but then failed on main. Reverting for now.
=> Revert "Bump prettier from 2.8.8 to 3.1.1"

.github/workflows/convert-to-js.yml
Changing how we run prettier for the JS conversion CI step - I'm not sure if this overrides other configs we might have had, but I believe it should lead to the same end result.
=> Fix issues when running prettier

vite.config.ts
In development mode, the Vite server will default to serving every file in the project folder, which we don't want since there are backend-only files in the repo.
Adding [`server.fs.allow`](https://vitejs.dev/config/server-options.html#server-fs-allow) rules for the files we do want to load, so that it more closely matches the production setup.
=> Restrict served files in dev mode

.prettierignore
JetBrains IDE tells me that these removed items are already covered by 'node_modules'. They seem to be right. When you run prettier, none of the files gets run.
=> Remove redundant ignores in .prettierignore

package.json
The `@remix-run/node` dependency requires `undici ^6.10.1`, which recently [dropped support for Node <18.17](https://github.com/nodejs/undici/pull/3125) in v6.14.
But the CLI should work with Node > 18.12, so initializing a Remix app with that Node version is currently crashing:
```
Error coming from `npm install`
Command failed with exit code 1: npm install
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: undici@6.14.1
npm ERR! notsup Not compatible with your version of node/npm: undici@6.14.1
npm ERR! notsup Required: {"node":">=18.17"}
npm ERR! notsup Actual:   {"npm":"8.19.2","node":"v18.12.0"}
```
Adds a resolution/override to pin Undici to 6.13.0, which [works with Node …
=> Pin Undici to 6.13

shopify.web.toml
The `prisma generate` command currently outputs a lot of information, which bloats the (already substantial) logs when an app starts. There is currently no way of turning down the amount of information it outputs, so we need to hide the output for now.
Using the `predev` command which will silently run a setup command before actually starting the server.
Before:
After:
```bash
npm init @shopify/app@latest -- --template=https://github.com/Shopify/shopify-app-template-remix.git#use_predev_command
```
=> Use CLI predev command

package.json
We recently updated the supported node versions because we needed specific versions of 18 and 20, but we accidentally ignored node 21 which should still work.
Making the engine version requirements a little more flexible so we don't have to worry about future versions.
```bash
npm init @shopify/app@latest -- --template=https://github.com/Shopify/shopify-app-template-remix.git#add_node_21_support
```
=> Allow using Node 21

app/routes/app._index.tsx
* useFetcher is the [recommended](https://remix.run/docs/en/main/discussion/form-vs-fetcher) way to submit data when you do not what to navigate away from the initial page.
* useFetcher will not change the URL
Fixes #0000 
```bash
shopify app init --template=https://github.com/Shopify/shopify-app-template-remix#liz/use-useFetcher
```
=> Use useFetcher instead of useSubmit for Product Creator

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
Fixes #771
It is currently difficult for devs to know when we've made changes to this template because:
- they need to manually check if something changed in the repo
- the actual changes aren't easy to find
Starting a changelog, which will be calver-based - so we won't track which changes are breaking or not as the only way apps can follow the template is by manually copying the changes.
Since this template is not supposed to be updated often, we shouldn't have to create too many releases for it.
=> Add changelog to track changes in repo

Dockerfile
Fixes #720 . Relates to previous attempts to reduce the file size on #418
* The docker image size for this app is ~ 1.8 GB
* I appears that most of this image size is unnecessary - the actually-used disk space on a running container is much smaller (~500 MB)
* After doing some digging, the main reason for this size is the node modules cache
* It seems like this gets included in the image unless `npm cache clean` gets run
* Additionally, if that line is not run in the same `RUN` as the `npm install`, then it will still show up in the docker image layer cache
* This PR proposes adding an `npm cache clean --force` to the `npm install` line
* The proposed strategy reduces image sizes down to ~ 500 MB.
* An additional part of this proposal is to only copy the package.json & lock files before …
=> Reduce docker image size:

.gitignore
* If multiple API keys/environments  are used for an app repo the CLI will create .env files with the API keys for each
* The format would be `.env.app-name`
Fixes #778 
```bash
```
=> Ignore all .env in gitignore

.gitignore
We're currently not ignoring pnpm lock files. This is removed by the CLI but might still be accidentally committed by developers using pnpm in this repo.
Adding the file to `.gitignore`.
=> Add pnpm lock file to gitignore

package.json
This PR updates the dependency on api-codegen-preset so we can fix the JS conversion workflow, which was failing due to mismatched types from that package.
=> Update api-codegen-preset package

CHANGELOG.md, app/routes/app._index.tsx
We're currently getting a warning in the template because we're using a deprecated GraphQL mutation.
Using the recommended alternative.
```bash
shopify app init --template=https://github.com/Shopify/shopify-app-template-remix#remove_deprecated_mutation
```
Run the app and see if it can still create a product.
=> [Chore] Stop using deprecated mutation

app/routes/webhooks.app.uninstalled.tsx, app/routes/webhooks.customers.data_request.tsx, app/routes/webhooks.customers.redact.tsx, app/routes/webhooks.shop.redact.tsx
The implementation for each webhook was a little inconsistent, which may have been confuding.
1. Always log the shop when logging inside a webhook handler
2. Always log use the payload (except for app uninstalled).  I didn't log the payload for this topic because it may fired when you run `npm run dev` and I didn't want the console to be too noisy.
3. Remove the shop check for shop redact since it was guarding agaisnt something that will be true (oops)
```bash
```
=> More consistent webhooks

app/db.server.ts
In the old code, two database connections get created in dev mode, which I think is not intentional.
Specifically:
1. On first load, the local `prisma` variable gets initialized to a new connection (as `global.prisma` is unset).
2. Since we are in dev mode, and `global.primsa` is not set, `global.prisma` gets initialized to yet another, fresh connection.
3. The first of these two connections gets exported and used.
4. For later HMR reloads, the 2nd connection is taken from `global.prisma`, means we have to DB connections being used in parallel.
This PR moves the global check to _after_ the dev mode check.
=> Fix race-y bug in db.server.ts

app/routes/webhooks.app.uninstalled.tsx
The afterAuth hook runs once on install. If a developer uninstalls and reinstalls, the afterAuth hook does not run because there is still a valid session. We need to properly await the deleting of sessions.
```bash
shopify app init --template=https://github.com/Shopify/shopify-app-template-remix#iphipps\/invalidate-session-on-uninstall
```
1. add a console log to an afterAuth hook in `app/shopify.server.ts` to see when it runs.  
2. notice how the afterAuth hook runs every time you install and uninstall the app on your store
Compare the behavior to `main` notice how afterAuth is run once.
=> await deleting the sessions on uninstall webhook

CHANGELOG.md, app/shopify.server.ts, package.json
- maintenance after shopify-app-remix release to 3.3.2
- version changes
```bash
```
=> Update API version and shopify-app-remix version

CHANGELOG.md, vite.config.ts
* Disable the singleFetch future flag while we determine the limitations with redirects.
```bash
```
=> Disable single fetch

CHANGELOG.md, app/routes/webhooks.app.scopes_update.tsx, shopify.app.toml
Implements [Shopify Remix template - Subscribe to the webhook event(s) sent when scopes are updated ](https://github.com/Shopify/develop-app-runtime-primitives/issues/340)
This adds the scopes-update webhook to the remix template, to allow the app to be notified and update its local database accordingly when a change in access scopes is made.
https://github.com/user-attachments/assets/6237fb5c-daf1-4fa7-8310-cdd5318ed349
```bash
shopify app init --template=https://github.com/Shopify/shopify-app-template-remix#add-scopes-update-webhook
```
Follow the instructions here to setup a optional scopes application with scopes revoke capabilities after scaffolding.
https://docs.google.com/spreadsheets/d/152j0NUJ-LjGKhgbQ73x_vPvcLJMRlcv7Dsip40dO5yE/edit?gid=1453682373#gid=1453682373
Alter the scopes …
=> Add Scopes Update Webhook to Remix Template

package.json
Reverts Shopify/shopify-app-template-remix#930
This upgrade caused this error when running: `shopify app init --template remix --flavor typescript`
```
Command failed with exit code 1: npm install
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: jan23-1048@undefined
npm error Found: @types/react@18.3.18
npm error node_modules/@types/react
npm error   dev @types/react@"^18.2.31" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @types/react@"^19.0.0" from @types/react-dom@19.0.3
npm error node_modules/@types/react-dom
npm error   dev @types/react-dom@"^19.0.1" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or …
```
=> Revert "Bump @types/react-dom from 18.3.5 to 19.0.1"

package.json
* They dropped node 18 support in a patch change
```
npm list graphql-ws                                                                                                                                                                                           ─╯
app@ /Users/lizkenyib/workspace/shopify-app-template-remix
└─┬ @shopify/api-codegen-preset@1.1.2
└─┬ @graphql-codegen/cli@5.0.3
└─┬ @graphql-tools/url-loader@8.0.16
└─┬ @graphql-tools/executor-graphql-ws@1.3.2
└── graphql-ws@5.16.0
```
```bash
shopify app init --template=https://github.com/Shopify/shopify-app-template-remix#liz/lock-graphql-url-loader-dependency
```
=> Lock @graphql-tools/url-loader dependency

vite.config.ts
In development its possible (but an edge case) that navigating from one page without these dependencies to another page with the dependencies would cause a full page refresh, which then redirects to the logicn page.  By adding this config, we should avoid that edge case
Adds 2 dependencies to optimize dependencies.
```bash
shopify app init --template=https://github.com/Shopify/shopify-app-template-remix#optimize-deps
```
=> Add app-bridge-react and polaris to optimizeDeps

app/db.server.ts
The Prisma client in `db.server.ts` file is currently attached to the global object as `prisma`, allowing it to be used in a file without an explicit import. This works in development environment, but causes the app to crash in production due to the missing import. This fix ensures that using prisma without importing it will fail locally as well, prompting developers to import it properly and preventing production errors.
This pull request renames the Prisma client object from `prisma` to `prismaGlobal` in the `db.server.ts` file.
=> Fix Prisma import issue in production

README.md
Correcting a minor typo. It should be "your" instead of "you".
Current version: "This only applies if you app is embedded" (INCORRECT)
Proposed update: "This only applies if your app is embedded" (CORRECT)
Fixes a misspelling, for cosmetic purposes only.
Adds `r` to the end of `you`:
```bash
```
=> Correct minor misspelling in README

README.md
The instructions to make the app non-embedded were incomplete
Add more complete instructions
```bash
```
Don't think we need these, but correct me if I'm wrong:
- ~~[ ] I have added an entry to `CHANGELOG.md`~~
- ~~[ ] I'm aware I need to create a new release when this PR is merged~~
=> Add some missing steps to the non-embedded instructions

.vscode/extensions.json
We added the dev assistant VSCode extension as a recommended extension on our remix app template. Since VSCode now have MCP support, that is our greenpath for developers building with Shopify.
Removing the dev assistant extension from the "recommended" extensions .
=> Remove extension recommendation

README.md
- Update the outdated reference to a single webhooks.tsx file
Update README.md
- Reflect current implementation which uses individual files for each webhook (webhooks.app.uninstalled.tsx and webhooks.app.scopes_update.tsx)
```bash
shopify app init --template=https://github.com/Shopify/shopify-app-template-remix#docs-webhook-routing
```
=> docs: update README description of webhooks implementation

CHANGELOG.md, package.json
Developers should use the global CLI installation
Fixes #0000 
```bash
shopify app init --template=https://github.com/Shopify/shopify-app-template-remix#remove-cli-dependency
```
=> Remove local CLI dependency

app/root.tsx, app/routes/app._index.tsx, app/routes/app.tsx, app/routes/auth.login/route.tsx
1. Fixes an issue where App Bridge & App Bridge components are loaded on the marketing index page.  App Bridge especially should not be loaded on the marketing page, because it is not embedded
2. Fixes a layout/design issue with the index page:
Before:
After:
1. Move App Bridge & Polaris web component into the app/ and login route rather than in root.tsx
2. Tweak design of the app index page
```bash
shopify app init --template=https://github.com/Shopify/shopify-app-template-remix#polaris-docs-2025-tweaks
```
N/A:
- ~~[ ] I have made changes to the `README.md` file and other related documentation, if applicable~~
- ~~[ ] I have added an entry to `CHANGELOG.md`~~
- ~~[ ] I'm aware I need to create a new release when this PR is merged~~
=> Polaris docs 2025 tweaks

.npmrc, CHANGELOG.md
https://github.com/Shopify/first-party-library-planning/issues/748
When using Node 24 we were seeing various warnings about npm config values that are no longer necessary.
* Removes `auto-install-peers` - this one was briefly an npm config but deprecated
* Removes `enable-pre-post-scripts` This was added when this template used a `predev` script in the `package.json`, that script in now run from the shopify.web.toml
* Removes `shamefully-hoist=true` not necessary with our tooling
```bash
shopify app init --template=https://github.com/Shopify/shopify-app-template-remix#resolve-npm-warnings
```
=> Remove deprecated npm config values

.graphqlrc.ts, CHANGELOG.md
Previously we configured `.graphqlrc` with the Shopify's `LATEST_API_VERSION`.  This is problematic because using `LATEST_API_VERSION` can incure breaking changes at the API layer, without the developer explicitly opting into those changes.
We now set an explicit version, just as we do in shopify.server.ts`
```bash
shopify app init --template=https://github.com/Shopify/shopify-app-template-remix#use-explicit-api-version
```
- ~~[ ] I have made changes to the `README.md` file and other related documentation, if applicable~~
- ~~[ ] I'm aware I need to create a new release when this PR is merged~~
=> Use an explicit API version to configure graphqlrc
