Shopify/shopify-app-template-remix

- remix.config.js
This PR just removes a TODO that was left over from development.
> Remove TODO

- README.md
Fixes #340  
It will fix the expired URL for Webhooks reference within the `README.md` and navigate users to the latest available version of the Docs within [`shopify-app-js` references](https://github.com/Shopify/shopify-app-js/tree/main/packages/shopify-app-remix#authenticating-webhook-requests).
> chore(readme): change webhooks reference

- .gitignore
This PR brings back gitignore config for local dev https://github.com/Shopify/shopify-app-template-remix/blob/399059825281578071aa904a5ba94415b5ca09e1/.gitignore#L7C1-L7C13
> chore: add path for local dev to gitignore

- app/routes/webhooks.tsx
- app/shopify.server.ts
We introduced a future flag for a more consistent Webhook Admin API.  Here I enable that feature flag.
Enables `v3_webhookAdminContext`.
> Use the V3 Webhook admin context

- README.md
Fix a broken link.
Replace the setup link — which currently doesn't lead anywhere in this file — to one that links to `Create an app` on Shopify's docs.
> [doc] Fix setup link in ReadMe

- app/entry.server.tsx
- package.json
Fixing broken developer experience after a breaking API change in `isbot` v4
- updated `isbot` import
- pinned package.json `isbot` to major version (4.1.0)
> [Fix] isbot v4 breaking change

- app/shopify.server.ts
* Update REST resources to latest version
* This will resolve some errors we are currently seeing in the logs
You can test this branch with the following command
```
npm init @shopify/app@latest -- --template=https://github.com/Shopify/shopify-app-template-remix.git#liz/update-rest-resources-2024-01
```
> Update REST resources to 2024-01

- .github/workflows/convert-to-js.yml
* We added a new `.ts` file at the root
* We need to remove this for the conversion the JS
* Remove the `.graphqlrc.ts` for the javascript version template
> Update the transpile job to remove the graphqlrc.ts

- README.md
Some links in the README.md are broken. 
Fix broken links
> [Fix] Fix links in README.md

- .github/workflows/convert-to-js.yml
- .graphqlrc.ts
* We were not transpiling  the `.graphqlrc.ts` file.
* There was a typescript error that was stopping the transpile from occuring
* Add `.graphqlrc.ts` to the list of files to be transpiled
* Add new types to the `graphqlrc.ts` file, to resolve type errors
> Add .graphqlrc to transpile job

- package.json
This PR updates the dependencies on Shopify packages to the latest versions.
> Update Shopify package dependencies

- app/shopify.server.ts
Enable new embedded auth strategy
Setting the `unstable_newEmbeddedAuthStrategy` to `true`
> Enable the new embedded authorization strategy by default

- app/routes/_index/route.tsx
- app/routes/_index/styles.module.css
- app/routes/app._index.tsx
- app/routes/app.tsx
- app/routes/auth.login/route.tsx
- app/shopify.server.ts
- package.json
- shopify.web.toml
- tsconfig.json
- vite.config.ts
Now that the template is running on Vite, there are a few things that we wanted to improve:
- We want to make sure HMR runs through WSS so it also works on Firefox and Safari
- We want to use CSS modules to not encourage folks to use global styles
Making those changes, plus a couple of stylistic tweaks to clean up the code.
> Fix FF HMR, and use CSS modules

- README.md
WIP To be released after releasing and updating the shopify-app-remix dependency
Related to #500 
Add docs for deploying to Vercel
> Add docs for deploying to Vercel

- .github/workflows/convert-to-js.yml
- app/routes/app._index.tsx
- app/routes/app.additional.tsx
- app/routes/app.tsx
- package.json
- tsconfig.json
As [App Bridge React v4](https://www.npmjs.com/package/@shopify/app-bridge-react) is now released, we should update this template to use it. This sets up developers to import components from `@shopify/app-bridge-react` without worrying about configuration.
It consumes the `@shopify/app-bridge-react` package and replaces the App Bridge web components with React wrappers. It also removes the `@shopify/app-bridge-types` package, as that's bundled up with `@shopify/app-bridge-react`.
> [Feature] Add App Bridge React v4

- .github/workflows/convert-to-js.yml
- app/routes/app._index.tsx
- app/routes/app.additional.tsx
- app/routes/app.tsx
- package.json
- tsconfig.json
Reverts Shopify/shopify-app-template-remix#577
> Revert "[Feature] Add App Bridge React v4"

- app/shopify.server.ts
* This flag will be turned on and removed in the next major release of Shopify-app-remix
* Enable this now in new templates so that app get access to this functionality by default.
Fixes #0000 
This PR can be tested with the following command
```
npm init @shopify/app@latest -- --template=https://github.com/Shopify/shopify-app-template-remix.git#liz/enable-v3_lineItemBilling
```
> Enable v3_lineItemBilling future flag by default

- app/shopify.server.ts
* The API version should be set to a specific version so breaking changes wont accidentally be brought in
> Set API version to April24

- .graphqlrc.ts
- app/shopify.server.ts
The API version should be set to a specific version so breaking changes wont accidentatlly be brought in
Fixes #0000 
> Fix API version to April 24

- .github/PULL_REQUEST_TEMPLATE.md
* I have to reference the format for testing with the CLI from a branch each time, so I thought we should just add it to the PR template.
> Update PR template to include test command

- app/routes/app._index.tsx
* Update the graphQL mutation operation  names so they are more easily identified in our logging.
Fixes #0000 
```bash
npm init @shopify/app@latest -- --template=https://github.com/Shopify/shopify-app-template-remix.git#<your-branch-name>
```
> Update GraphQL operation names

- .github/workflows/convert-to-js.yml
- app/routes/app._index.tsx
- app/routes/app.additional.tsx
- app/routes/app.tsx
- package.json
- tsconfig.json
As [App Bridge React v4](https://www.npmjs.com/package/@shopify/app-bridge-react) is now released, we should update this template to use it. This sets up developers to import components from `@shopify/app-bridge-react` without worrying about configuration.
It consumes the `@shopify/app-bridge-react` package and replaces the App Bridge web components with React wrappers. It also removes the `@shopify/app-bridge-types` package, as that's bundled up with `@shopify/app-bridge-react`.
```
npm init @shopify/app@latest -- --template=https://github.com/Shopify/shopify-app-template-remix.git#cd/app-bridge-react-v4
```
> [Feature] add `@shopify/app-bridge-react@4`

- README.md
* Developers have run into issues moving from Prisma + SQLite to Prisma + MongoDB
* Developers should reference the Prisma documentation, for configuring Prisma + MongoDB
> [Docs] Add information for connecting to MongoDB

- shopify.app.toml
> Remove privacy compliance topics from the default TOML

- README.md
Fixes https://github.com/Shopify/shopify-app-template-remix/issues/354, see my last comment
Adds necessary modification to Readme
```bash
```
> Update Readme to provide solution for Prisma & MongoDB migration issue

- app/routes/_index/route.tsx
- app/routes/app._index.tsx
- app/routes/app.tsx
- app/routes/auth.$.tsx
- app/routes/auth.login/route.tsx
- app/routes/webhooks.tsx
- app/shopify.server.ts
https://github.com/Shopify/shopify-app-template-remix/pull/757
↑ This change brings the following changes to javascript
https://github.com/Shopify/shopify-app-template-remix/pull/766/files
This is not interpreted correctly by javascript and an error will occur if the specified module is not found
As you can see, sir.
> [FIX] File path

- CHANGELOG.md
> Update changelog for new indivual webhook routes

- CHANGELOG.md
- app/shopify.server.ts
- shopify.app.toml
- updating rest resources version
- flagged here: https://github.com/Shopify/shopify-app-template-remix/pull/863#issuecomment-2500246901
```bash
shopify app init --template=https://github.com/Shopify/shopify-app-template-remix#andy-liuu/update-rest-resources-2024-10
```
> Update rest resource version to 2024-10

- CHANGELOG.md
- package.json
Fixes #0000 
```bash
shopify app init --template=https://github.com/Shopify/shopify-app-template-remix#update-shopify-prisma-dependency
```
> Update the shopify app prisma package

- .vscode/mcp.json
- CHANGELOG.md
Since Shopify recommends Shopify MCPs in all new projects, it makes sense to have it added to the app template.
It's adding a mcp.json file to add Shopify MCP server config.
```bash
shopify app init --template=https://github.com/rafaelstz/shopify-app-template-remix#add-shopify-mcp
```
> Add Shopify MCP to VSCode configs

- .github/dependabot.yml
See: https://github.com/Shopify/shopify-app-js/pull/2744
See: https://github.com/Shopify/shopify-app-js/pull/2744
```bash
```
N/A - internal change only
> Remove increase-if-necessary
